const routes = {
  home: '/home',
  weapons: '/weapons',
  horses: '/horses',
  storyQuests: '/story-quests',
  sideQuests: '/side-quests',
  animals: '/animals',
  plants: '/plants',
  fishes: '/fishes',
  challenges: '/challenges',
  collectibles: '/collectibles',
  factions: '/factions',
  miscellaneous: '/miscellaneous',
  randomEncounters: '/randomEncounters',
  tableGames: '/tableGames',
  detailedWeapon: '/weapons/:id',
  detailedHorse: '/horses/:id',
  detailedStoryQuest: '/story-quests/:id',
  detailedSideQuest: '/side-quests/:id',
  detailedAnimal: '/animals/:id',
  detailedPlant: '/plants/:id',
  detailedFish: '/fishes/:id',
  detailedCollectible: '/collectibles/:id',
  saved: '/saved',
  login: '/login',
  registration: '/registration',
  account: '/account',
};

export default routes;
